"""init

Revision ID: 325c050e21b2
Revises: b676c4883225
Create Date: 2023-12-03 15:50:04.835925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325c050e21b2'
down_revision: Union[str, None] = 'b676c4883225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_ask', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('product_bid', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_bid', 'is_active')
    op.drop_column('product_ask', 'is_active')
    # ### end Alembic commands ###
