"""init

Revision ID: 4333d8c4dbd2
Revises: c7cbf5b286a5
Create Date: 2023-12-04 13:21:27.298203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4333d8c4dbd2'
down_revision: Union[str, None] = 'c7cbf5b286a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('min_ask_price', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('min_ask_id', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('max_bid_price', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('max_bid_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'bid', ['max_bid_id'], ['id'])
    op.create_foreign_key(None, 'product', 'ask', ['min_ask_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'max_bid_id')
    op.drop_column('product', 'max_bid_price')
    op.drop_column('product', 'min_ask_id')
    op.drop_column('product', 'min_ask_price')
    # ### end Alembic commands ###
